### ISSUE TITLE
Step 6 GET should be POST

### ISSUE THREAD

**Issue by Vinecnt** [kevinjalbert/notion-heroku#7]
In "Step 6 - Complete Webhook Action Fields", the image indicated the web request to be GET. But route accepts only POST. Editting the image may be annoying so adding a little note may be enough instead. 
![image](https://user-images.githubusercontent.com/14827962/70575020-81238880-1b73-11ea-91b4-de6c0d3e440e.png)

**Comment by kevinjalbert** [comment]
As mentioned in https://github.com/kevinjalbert/notion-heroku/issues/8#issuecomment-564325136.

> this is an artifact of me not getting around to updating the steps and images. I've since made changes so that these endpoints accept data via POST...

> This is expected behaviour at this point, and the issue is in the README. I'll see to updating it within the next few days as this is the second time this came up via an issue.

------

Much appreciated for raising this to my attention though, it is showing the gap in the README.

**Comment by Vinecnt** [comment]
No problem. It's a great project
